[package]
name = "rustest"
version = "0.1.0"
authors = ["Zhijie Shen <zjshen14@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vm_runtime_tests = { git = "https://github.com/libra/libra" }